Script started on Mon 25 Oct 2021 10:24:05 PM EDT
cis-lclient02:~/CIS1057/lab6>exit./a.out[30Ggcc lab6/lab6driver.c -lm[P[P[P[P[P
cis-lclient02:~/CIS1057/lab6>gcc lab6driver.c -lm[30Gexit[K./a.out
This purpose of this program is to Numeric tables generated on demand make it easy to understand the relation between ranges of numbers at a glance.
This program was written by Ben Fasick on Monday October 18th.
The following operators and their meanings are supported:
  +: addition
  -: subtraction
  x,X,*: multiplication
  /: division
  D: integer division
  %: modulo
  p: row value raised to the column power
  r: column root of the row value
  h: display this message

x = -2 to 3
y = 1 to 5
operator = '+'
+           1           2           3           4           5           
-2          -1          0           1           2           3           
-1          0           1           2           3           4           
0           1           2           3           4           5           
1           2           3           4           5           6           
2           3           4           5           6           7           
3           4           5           6           7           8           

x = -7 to -1
y = -1 to 3
operator = '-'
-           -1          0           1           2           3           
-7          -6          -7          -8          -9          -10         
-6          -5          -6          -7          -8          -9          
-5          -4          -5          -6          -7          -8          
-4          -3          -4          -5          -6          -7          
-3          -2          -3          -4          -5          -6          
-2          -1          -2          -3          -4          -5          
-1          0           -1          -2          -3          -4          

x = -5 to 1
y = -1 to 3
operator = 'x'
x           -1          0           1           2           3           
-5          5           0           -5          -10         -15         
-4          4           0           -4          -8          -12         
-3          3           0           -3          -6          -9          
-2          2           0           -2          -4          -6          
-1          1           0           -1          -2          -3          
0           0           0           0           0           0           
1           -1          0           1           2           3           

x = 5 to 9
y = 1 to 5
operator = 'X'
X           1           2           3           4           5           
5           5           10          15          20          25          
6           6           12          18          24          30          
7           7           14          21          28          35          
8           8           16          24          32          40          
9           9           18          27          36          45          

x = 7 to 11
y = 3 to 5
operator = '*'
*           3           4           5           
7           21          28          35          
8           24          32          40          
9           27          36          45          
10          30          40          50          
11          33          44          55          

x = 1 to 5
y = -1 to 4
operator = '/'
/               -1              0               1               2               3               4               
1               -1.000000       inf             1.000000        0.500000        0.333333        0.250000        
2               -2.000000       inf             2.000000        1.000000        0.666667        0.500000        
3               -3.000000       inf             3.000000        1.500000        1.000000        0.750000        
4               -4.000000       inf             4.000000        2.000000        1.333333        1.000000        
5               -5.000000       inf             5.000000        2.500000        1.666667        1.250000        

x = -1 to 3
y = 4 to 8
operator = 'D'
D           4           5           6           7           8           
-1          0           0           0           0           0           
0           0           0           0           0           0           
1           0           0           0           0           0           
2           0           0           0           0           0           
3           0           0           0           0           0           

x = 2 to 5
y = 1 to 6
operator = '%'
%           1           2           3           4           5           6           
2           0           0           2           2           2           2           
3           0           1           0           3           3           3           
4           0           0           1           0           4           4           
5           0           1           2           1           0           5           

x = -2 to 4
y = -2 to 3
operator = 'p'
p           -2          -1          0           1           2           3           
-2          0           0           1           -2          4           -8          
-1          1           -1          1           -1          1           -1          
0           -2147483648 -2147483648 1           0           0           0           
1           1           1           1           1           1           1           
2           0           0           1           2           4           8           
3           0           0           1           3           9           27          
4           0           0           1           4           16          64          

x = -1 to 4
y = -3 to 2
operator = 'r'
r               -3              -2              -1              0               1               2               
-1              -1.000000       1.000000        -1.000000       1.000000        -1.000000       1.000000        
0               inf             inf             inf             1.000000        0.000000        0.000000        
1               1.000000        1.000000        1.000000        1.000000        1.000000        1.000000        
2               0.125000        0.250000        0.500000        1.000000        2.000000        4.000000        
3               0.037037        0.111111        0.333333        1.000000        3.000000        9.000000        
4               0.015625        0.062500        0.250000        1.000000        4.000000        16.000000       

cis-lclient02:~/CIS1057/lab6>exit
exit

Script done on Mon 25 Oct 2021 10:24:36 PM EDT
